[package]
name = "lexer"
version = "0.1.0"
authors = ["Rodrigo <rodrigomauricio@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base-x = "0.2.0"
